id = "ilk"
name = "Ilk"
description = "Syntax highlighting for Ilk documents and meta files."
version = "0.1.0"
schema_version = 1
authors = ["trnglina"]

[grammars.ilk]
repository = "file:///Users/trnglina/Developer/tree-sitter-ilk"
rev = "ddd42d40d80387a15c421b48503ccb6ab91ea898"
path = "ilk"

[grammars.ilk_meta]
repository = "file:///Users/trnglina/Developer/tree-sitter-ilk"
rev = "ddd42d40d80387a15c421b48503ccb6ab91ea898"
path = "ilk_meta"
