name = "Ilk Meta"
grammar = "ilk_meta"
path_suffixes = ["ilkm"]
word_characters = ["$", "?", "#"]
block_comment = { start = "/*", end = "*/", prefix = "* ", tab_size = 1 }
autoclose_before = ";,)"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
